# NOTE: This is my GPU setup with my indexes. Make sure they match up to yours
# index 0: 3070 (9652988c-23cb-3d44-92f1-fe4b3189f334)
# index 1: 3060 ti (c5bc98c1-e7c9-a438-3cc5-56362e4eab24)
# index 2: 3060 (8b6de0bb-89ad-1f78-1c8b-34f0e740e1ca)
# index 3: 3060 (93546bb2-97df-8ac3-2941-6e8be8aef53c)
# index 4: 2060 (988d240c-f178-4b8f-eb54-d831f3d0f1a5)

---
version: '3.8'
services:


  # https://hub.docker.com/r/ollama/ollama
  ollama-code:
    container_name: ollama-code
    restart: unless-stopped
#    user: 1000:1000
    image: ollama/ollama
    volumes:
      - "./.ollama-code:/root/.ollama"
    ports:
      - 11435:11434
    deploy:
      resources:
        reservations:
           devices:
              - driver: nvidia
                device_ids: [ '1', '2' ]
                capabilities: [gpu]

  ollama:
    container_name: ollama
    restart: unless-stopped
#    user: 1000:1000
    image: ollama/ollama
    volumes:
      - "./.ollama:/root/.ollama"
    expose:
      - 11434
    ports:
      - 11433:11434
    deploy:
      resources:
        reservations:
           devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
