# See README.md for devices and how to get their IDs

---
version: '3.8'
services:


  # https://hub.docker.com/r/ollama/ollama
  ollama-code:
    container_name: ollama-code
    restart: unless-stopped
    image: ollama/ollama
    volumes:
      - "./.ollama-code:/root/.ollama"
    ports:
      - 11435:11434
    deploy:
      resources:
        reservations:
           devices:
              - driver: nvidia
                device_ids: [ '1', '2' ]
                capabilities: [gpu]

  ollama:
    container_name: ollama
    restart: unless-stopped
    image: ollama/ollama
    volumes:
      - "./.ollama:/root/.ollama"
    expose:
      - 11434
    ports:
      - 11433:11434
    deploy:
      resources:
        reservations:
           devices:
              - driver: nvidia
                device_ids: ['4']
                capabilities: [gpu]
