
version: '3.8'
services:


  # https://github.com/open-webui/open-webui
  open-webui:
    container_name: open-webui
    restart: unless-stopped
#    user: 1000:1000
    image: ghcr.io/open-webui/open-webui:main
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    volumes:
      - "./.open-webui:/app/backend/data"
    ports:
      - 8081:8080
    depends_on:
      - ollama